// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSysPreFinals.Models;

public partial class Course
{
    public int course_id { get; set; }

    public string course_name { get; set; }

    public string course_description { get; set; }

    public int? credits { get; set; }

    public string department { get; set; }

    public string semester { get; set; }
}