// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSysPreFinals.Models;

public partial class Room
{
    public int room_id { get; set; }

    public string room_name { get; set; }

    public string room_building { get; set; }

    public int? capacity { get; set; }
}