// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSysPreFinals.Models;

public partial class Section
{
    public int section_id { get; set; }

    public int course_id { get; set; }

    public int teacher_id { get; set; }

    public int room_id { get; set; }

    public int capacity { get; set; }

    public string schedule { get; set; }

    public string section_number { get; set; }
}