// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSysPreFinals.Models;

public partial class Student
{
    public int student_id { get; set; }

    public string first_name { get; set; }

    public string last_name { get; set; }

    public string email { get; set; }

    public DateOnly birth_date { get; set; }

    public int phone_number { get; set; }

    public string address { get; set; }
}