// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebSysPreFinals.Models;

public partial class StudInfoSysContext : DbContext
{
    public StudInfoSysContext(DbContextOptions<StudInfoSysContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<Section> Sections { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Teacher> Teachers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.course_id);

            entity.ToTable("Course");

            entity.Property(e => e.course_id).ValueGeneratedNever();
            entity.Property(e => e.course_description)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.course_name)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.department)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.semester)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Room>(entity =>
        {
            entity.HasKey(e => e.room_id);

            entity.ToTable("Room");

            entity.Property(e => e.room_id).ValueGeneratedNever();
            entity.Property(e => e.room_building)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.room_name)
                .HasMaxLength(10)
                .IsFixedLength();
        });

        modelBuilder.Entity<Section>(entity =>
        {
            entity.HasKey(e => e.section_id);

            entity.ToTable("Section");

            entity.Property(e => e.section_id).ValueGeneratedNever();
            entity.Property(e => e.schedule)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.section_number)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.student_id);

            entity.ToTable("Student");

            entity.Property(e => e.student_id).ValueGeneratedNever();
            entity.Property(e => e.address)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.email)
                .IsRequired()
                .HasMaxLength(55)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.first_name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.last_name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Teacher>(entity =>
        {
            entity.HasKey(e => e.teacher_id);

            entity.ToTable("Teacher");

            entity.Property(e => e.teacher_id).ValueGeneratedNever();
            entity.Property(e => e.department)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.email)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.first_name)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.last_name)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}