// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebSysPreFinals.Models;

public partial class Teacher
{
    public int teacher_id { get; set; }

    public string first_name { get; set; }

    public string last_name { get; set; }

    public string email { get; set; }

    public int? phone_number { get; set; }

    public string department { get; set; }
}